#!/usr/bin/env bash
# Creating a configuration file for the redirection me to another page
# The redirection must be a “301 Moved Permanently”

CONFIG_FILE="/etc/nginx/sites-available/default"
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Applying update and istalling nginx if not installed
if ! [ -x "$(command -v nginx)" ]; then
	sudo apt-get update
	sudo apt-get -y install nginx
fi

service nginx start

REDIRECT_CONFIG="location /redirect_me {
	return 301 $REDIRECT_URL permanent;
}"

# Adding redirection configuration to nginx config file
sed -i "$REDIRECT_CONFIG" "$CONFIG_FILE"

sudo systemctl reload nginx
