#!/usr/bin/env bash
# Creating a configuration file for the redirection me to another page
# The redirection must be a “301 Moved Permanently”

# Updating snd Installing nginx
apt-get update
apt-get -y install nginx

# Allowing the Nginx for firewalls
sudo ufw allow 'Nginx HTTP'

# Making directories
mkdir -p /var/www/html/

# change directory permissin
sudo chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html

NGINX_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}

	if (\$request_filename ~ redirect_me){
		rewrite ^ https://github.com/njdam permanent;
	}
}"

# Replacing process
bash -c "echo -e '$NGINX_CONFIG' > /etc/nginx/sites-enabled/default"

# Applying the chsnges by starting or restarting
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
