#!/usr/bin/env bash
# Configuration of new webserver to Run Nginx and set up it's HTTP response
# To contain a custom header

# Updating and installing nginx server
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start

# Replacing the Current header with custom header
sed -i "20i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Restaring nginx web server
sudo service nginx restart
