#!/usr/bin/env bash
# A Bash script that install and setting up load balancer HAproxy

# Updating and Installing HAproxy load balancer
sudo apt-get update
sudo apt-get -y install haproxy

# The configuration of haproxy load balancer
DOMAIN_NAME='jeandamn.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_CONFIG=\
"
#--$DOMAIN_NAME-config-begin---
frontend web_front
	bind *:80
	default_backend web_back

backend web_back
	mode http
	balance roundrobin
	server web1 52.72.28.52:80 check
	server web2 100.26.239.179:80 check
#--$DOMAIN_NAME-config-end--
"

# Addition Configuration under defaults for Monitoring HAproxy load blancer
#INSERT_CONFIG=$'\n\tstats enable\n\tstats uri /haproxy?stats'
#sudo sed '/^defaults$/a$INSERT_CONFIG' $INIT_FILE > temp_file && mv temp_file $INIT_FILE

# Enabling the Haproxy to work
sudo sed -i 's/ENABLED=0/ENABLED=1/' $INIT_FILE

# Searching my Configuration Word as domain name if found means configured
CONFIG_WORD=$(grep -Eco "$DOMAIN_NAME" < $CONFIG_FILE)
if [ "$CONFIG_WORD" -eq 0 ]; then
	echo -en "$HAPROXY_CONFIG" >> $CONFIG_FILE
fi

# Restarting or starting haproxy load balancer
if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
