#!/usr/bin/env bash
# A Load balancer server configuration

# Starting up the ssh agent
eval $("ssh-agent")

# Path to file identification
ssh-add ~/.ssh/school

# Username and Ip Adress for load balancer server
ssh ubuntu@54.89.195.78
