#!/usr/bin/env bash
# Server 02 login configuration

# Setting up the ssh agent
eval $("ssh-agent")

# Path to the Identity file
ssh-add ~/.ssh/school

# Username and Ip address for web-server 02
ssh ubuntu@100.26.239.179
