#!/usr/bin/env bash
# Server 01 login configuration

# Setting up the ssh agent
eval $("ssh-agent")

# Path to the Identity file
ssh-add ~/.ssh/school

# Username and Ip address for web-server 01
ssh ubuntu@52.72.28.52
