#!/usr/bin/env bash
# A Bash script to generate MySQL dump & create compressed archive out of it
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -cvzf "$(date '+%d-%m-%Y.tar.gz')" backup.sql
