#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
ln -sf //etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart  # restarting nginx
kill "$(pgrep 'nginx' | head -1)"  # Terminating nginx 1st process
