#!/usr/bin/env bash
# A Bash script to create the file /var/run/myscript.pid containing its PID
# and displays To infinity and beyond indefinitely, and display:
# I hate the kill command when receiving a SIGTERM signal;
# Y U no love me?! when receiving a SIGINT signal;
# and Deletes the file /var/run/myscript.pid and
# terminates itself when receiving a SIGQUIT or SIGTERM signal

terminate()
{
	rm /var/run/myscript.pid
	exit
}

echo $$ >> /var/run/myscript.pid

while true;
do
	echo "To infinity and beyond"
	sleep 2
	# When receiving a signal SIGTERM (15) or SIGINT (2) or SIGQUIT (3)
	trap "echo 'I hate the kill command' && terminate" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap "terminate" SIGQUIT
done
