#!/usr/bin/env bash
# A Bash script that displays lines containing the bash word,
# thus allowing you to easily get the PID of your Bash process.

# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
