#!/usr/bin/env bash
# A Bash script that stops 4-to_infinity_and_beyond process.

kill $(ps -x | pgrep -f infinity)
# or kill $(ps -x | pgrep -f beyond)
# this stop every thing plus terminal `kill $(ps -x | pgrep -f and)`
