#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100 and displays:
# FizzBuzz when the number is a multiple of 3 and 5
# Fizz when the number is multiple of 3
# Buzz when the number is a multiple of 5
# Otherwise, displays the number In a list format

((i = 1))
while [ $i -le 100 ];
do
	if ((i % 3 == 0 &&  i % 5 == 0)); then
		echo "FizzBuzz"

	elif ((i % 3 == 0)); then
		echo "Fizz"

	elif ((i % 5 == 0)); then
		echo "Buzz"

	else
		echo "$i"
	fi

	((i++))
done
