#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 and displays:
# 4 and bad luck from China for the 4th loop iteration,
# 9 and bad luck from Japan for the 9th loop iteration, and
# 17 and bad luck from Italy for the 9th loop iteration, and

((i = 1))
while [ $i -le 20 ];
do
	echo "$i"

	case $i in
		4)
			echo "bad luck from China"
			;;

		9)
			echo "bad luck from Japan"
			;;

		17)
			echo "bad luck from Italy"
			;;
	esac

	((i++))
done
