#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes

((j = 0))
while [ $j -le 12 ];
do
	echo "Hour: $j"

	((i = 1))
	while [ $i -le 59 ];
	do
		echo "$i"

		((i++))
	done

	((j++))
done
