#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
# (refer to the example)

list=$(ls)
for file in $list;
do
	echo "$file" | cut -d '-' -f2
done
