#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements

cp /etc/hosts ~/hosts.temp
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.temp
echo '8.8.8.8	facebook.com' >> ~/hosts.temp
cp -f ~/hosts.temp /etc/hosts
rm ~/hosts.temp
