#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements

cp /etc/hosts /etc/hosts.bak

sed -i 's/localhost/127.0.0.2/g' /etc/hosts
sed -i 's/facebook.com/8.8.8.8/g' /etc/hosts

systemctl restart systemd-resolved.service
