#!/usr/bin/env bash
# A Bash script that displays all active IPv4 IPs
# on the machine it’s executed on.

ifconfig | grep 'inet ' | awk '{print $2}'
# or this `ifconfig -a | grep 'inet ' | awk '{print $2}'`
# or this `ip -4 addr | grep 'inet ' | awk '{print $2}' | cut -d "/" -f1`
