#!/usr/bin/env bash
# Fixing the container so that Nginx is running as the nginx user
chmod 644 /etc/nginx/nginx.conf
# Replacing the user in nginx server in container as nginx user
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
