#!/usr/bin/env bash
# A Bash script tells the master Gunicorn renewed all the workers.
sudo nohup pkill -HUP -f '[g]unicorn' > /dev/null 2>&1 &
# 3. Send the USR2 signal to the master process to gracefully reload workers
#kill -s USR2 "$gunicorn_master_pid"
