#!/usr/bin/env bash
# A bash script that creates an RSA key pair.
ssh-keygen -t rsa -b 4096 -f school -N betty
# Where `-t` specify type key to be created
#       `-b` specifies the number of bits in the key
#       `-f` specifies the filename of generated key pair
#       `-N` specifies the passphrase for the private key (or password)
